name: Build Godot Project

on: 
  push

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, linux]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        id: build
        uses: QuakeEye/godot-mono-build-action@v0.1.1
        with:
          name: launcher
          preset: ${{ matrix.platform }}
          debugMode: true
          runVerbose: true
          isWindows: ${{ matrix.platform == 'windows' }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}