name: Build Godot Project

on: push

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, mac, linux]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: QuakeEye/godot-mono-build-action@v0.0.3
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
          runVerbose: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}